version: '3.9'

services:
    # bap-service:
    #   container_name: bap-service
    #   image: becknbros/bap-service
    #   restart: always
    #   build: .
    #   volumes:
    #     - .:/usr/src/app
    #   environment:
    #     - MONGO_INITDB_ROOT_USERNAME=rootuser
    #     - MONGO_INITDB_ROOT_PASSWORD=rootpass
    #   ports:
    #     - 4567:4567
    #   links:
    #     - mongodb

    redis:
      image: redis:7.0.4
      container_name: redis
      ports:
        - 6379:6379
      command: '--requirepass password'
      volumes:
        - redis:/data

    mongo:
      image: mongo
      container_name: mongodb
      ports:
        - "27017:27017"
      volumes:
        - mongodata:/data/db

    mongo-express:
      image: mongo-express
      restart: always
      ports:
        - 18081:8081

volumes:
  mongodata:
  redis: